before_script:
  - sudo apt-get -y -q install curl make

script:
  - export PATH=$PATH:$PWD/bin:$PWD/sam
  - make rescue
  - git clone --depth=1 git://github.com/nddrylliog/sam.git 
  - (cd sam && rock -v)
  - sam test

notifications:
  webhooks: http://rcmp.pw/freenode/ooc-lang

